### ISSUE TITLE
One last dot

### ISSUE THREAD

**Issue by dcfidalgo** [halirutan/VariableDensitySubsampling#5]
Using the interface in the training seems to work fine, there is a small difference though. I noticed that the executable always sets the point in the center to 0, while the interface doesn't ... @halirutan @kornelius (@spam-depository ?) Do you know what could be the reasoning behind setting the center to 0?

interface: 
![interface](https://user-images.githubusercontent.com/15979778/212026109-0e494dac-8a6f-487b-bc0d-3ce0f3807756.png)

executable:
![executable](https://user-images.githubusercontent.com/15979778/212026446-f77edb57-9f9a-4c6a-ad71-8b63dd2bbf2a.png)

**Comment by spam-depository** [comment]
k-space center is the zero frequency. since single mri measurements
do not produce comparable values the absolute value is not relevant.
thus trying to remove sampling points the zero might be an easy target.
in consequence by removing the zero frequency one should get zero mean
images...

**Comment by halirutan** [comment]
After a whole night of debugging and writing an additional small program to create the subsample mask directly with a C program, I found the culprit. So if you ask yourself why our sampling mask doesn't contain the missing zero frequency, it is because this point is left out **during the writing of the `samplingPattern.txt` file! [Look here](https://github.com/thomaskuestner/CS_MoCo_LAB/blob/a26e8e483624b2e4ee669e7a069ba9c74d2d2e4b/acquisition/subsampling_class/VDSamplingUpper.cpp#L708).

Now that we know that this is not a bug in our code but rather done after the sampling mask is already created here is a question to @spam-depository: Should I also always leave the central point out?
